/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package twentyone-0.1.0.0 */
#ifndef VERSION_twentyone
#define VERSION_twentyone "0.1.0.0"
#endif /* VERSION_twentyone */
#ifndef MIN_VERSION_twentyone
#define MIN_VERSION_twentyone(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_twentyone */

/* package base-4.14.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 1)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package cassava-0.5.2.0 */
#ifndef VERSION_cassava
#define VERSION_cassava "0.5.2.0"
#endif /* VERSION_cassava */
#ifndef MIN_VERSION_cassava
#define MIN_VERSION_cassava(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 2)
#endif /* MIN_VERSION_cassava */

/* package containers-0.6.2.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.2.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 2)
#endif /* MIN_VERSION_containers */

/* package deepseq-1.4.4.0 */
#ifndef VERSION_deepseq
#define VERSION_deepseq "1.4.4.0"
#endif /* VERSION_deepseq */
#ifndef MIN_VERSION_deepseq
#define MIN_VERSION_deepseq(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_VERSION_deepseq */

/* package directory-1.3.6.0 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.6.0"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_directory */

/* package filepath-1.4.2.1 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.1"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */

/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */

/* package random-1.1 */
#ifndef VERSION_random
#define VERSION_random "1.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package time-1.9.3 */
#ifndef VERSION_time
#define VERSION_time "1.9.3"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 3)
#endif /* MIN_VERSION_time */

/* package utility-ht-0.0.15 */
#ifndef VERSION_utility_ht
#define VERSION_utility_ht "0.0.15"
#endif /* VERSION_utility_ht */
#ifndef MIN_VERSION_utility_ht
#define MIN_VERSION_utility_ht(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 15)
#endif /* MIN_VERSION_utility_ht */

/* package vector-0.12.1.2 */
#ifndef VERSION_vector
#define VERSION_vector "0.12.1.2"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 1)
#endif /* MIN_VERSION_vector */

/* tool doctest-0.16.3 */
#ifndef TOOL_VERSION_doctest
#define TOOL_VERSION_doctest "0.16.3"
#endif /* TOOL_VERSION_doctest */
#ifndef MIN_TOOL_VERSION_doctest
#define MIN_TOOL_VERSION_doctest(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  16 || \
  (major1) == 0 && (major2) == 16 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_doctest */

/* tool gcc-9.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "9.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool runghc-8.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.32 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.32"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  32 || \
  (major1) == 2 && (major2) == 32 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "twentyone-0.1.0.0-5AZpwtyjgn1BoTFmYjrbhL"
#endif /* CURRENT_PACKAGE_KEY */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "twentyone-0.1.0.0-5AZpwtyjgn1BoTFmYjrbhL"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package twentyone-0.1.0.0 */
#ifndef VERSION_twentyone
#define VERSION_twentyone "0.1.0.0"
#endif /* VERSION_twentyone */
#ifndef MIN_VERSION_twentyone
#define MIN_VERSION_twentyone(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_twentyone */

/* package base-4.14.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.14.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  14 || \
  (major1) == 4 && (major2) == 14 && (minor) <= 1)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.12.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.12.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 12)
#endif /* MIN_VERSION_bytestring */

/* package cassava-0.5.2.0 */
#ifndef VERSION_cassava
#define VERSION_cassava "0.5.2.0"
#endif /* VERSION_cassava */
#ifndef MIN_VERSION_cassava
#define MIN_VERSION_cassava(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 2)
#endif /* MIN_VERSION_cassava */

/* package containers-0.6.2.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.2.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 2)
#endif /* MIN_VERSION_containers */

/* package deepseq-1.4.4.0 */
#ifndef VERSION_deepseq
#define VERSION_deepseq "1.4.4.0"
#endif /* VERSION_deepseq */
#ifndef MIN_VERSION_deepseq
#define MIN_VERSION_deepseq(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_VERSION_deepseq */

/* package directory-1.3.6.0 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.6.0"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_directory */

/* package filepath-1.4.2.1 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.1"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */

/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */

/* package random-1.1 */
#ifndef VERSION_random
#define VERSION_random "1.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package time-1.9.3 */
#ifndef VERSION_time
#define VERSION_time "1.9.3"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 3)
#endif /* MIN_VERSION_time */

/* package twentyone-0.1.0.0 */
#ifndef VERSION_twentyone
#define VERSION_twentyone "0.1.0.0"
#endif /* VERSION_twentyone */
#ifndef MIN_VERSION_twentyone
#define MIN_VERSION_twentyone(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_twentyone */

/* package utility-ht-0.0.15 */
#ifndef VERSION_utility_ht
#define VERSION_utility_ht "0.0.15"
#endif /* VERSION_utility_ht */
#ifndef MIN_VERSION_utility_ht
#define MIN_VERSION_utility_ht(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 15)
#endif /* MIN_VERSION_utility_ht */

/* package vector-0.12.1.2 */
#ifndef VERSION_vector
#define VERSION_vector "0.12.1.2"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 1)
#endif /* MIN_VERSION_vector */

/* tool doctest-0.16.3 */
#ifndef TOOL_VERSION_doctest
#define TOOL_VERSION_doctest "0.16.3"
#endif /* TOOL_VERSION_doctest */
#ifndef MIN_TOOL_VERSION_doctest
#define MIN_TOOL_VERSION_doctest(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  16 || \
  (major1) == 0 && (major2) == 16 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_doctest */

/* tool gcc-9.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "9.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.24.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.24.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  24 || \
  (major1) == 2 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.7 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.7"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool runghc-8.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  10 || \
  (major1) == 8 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.32 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.32"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  32 || \
  (major1) == 2 && (major2) == 32 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "twentyone-0.1.0.0-AFHQ6TVmhKk3RU0HPDbGkE-staticgame"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
